kind: Service
apiVersion: v1
metadata:
  name: webform
spec:
  selector:
    app: webform
    track: production
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
      nodePort: 31000
  type: NodePort
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: webform
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: webform
        tier: frontend
        track: production
    spec:
      containers:
        - name: webform
          image: "jonathanfane/webform"
          ports:
            - name: http
              containerPort: 80
