apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: webform-canary
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: webform
        tier: frontend
        track: canary
    spec:
      containers:
        - name: webform
          image: "jonathanfane/webform"
          ports:
            - name: http
              containerPort: 80
