kind: Service
apiVersion: v1
metadata:
  name: webform
spec:
  selector:
    app: webform
    track: production
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
      nodePort: 31000
  type: NodePort


